---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss
  namespace: media
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
