---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml

# Creates a ConfigMap from the values file, `kube-state-metrics-config.yaml` using the ConfigMap object in `kustomizeconfig.yaml`
#
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomizeconfig.yaml
