apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:z4D1RvOpwgiGfCuamIpZE1LAP1NZUYgS/566OXeX/stSB86U,iv:nb7vfSN7y9aDk7GnLv/0pvuGADX6nPrB7WwRn1P3Y9M=,tag:to4mredn22su/SR/G7WlIg==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:2vvK/6X++W0TEqkIK4FBEFVmCwEYzSWFUlpZbF4hjIQHHS0ofGiyBk3fzU5PFYPUVN/Hgd3oMwkBSgbUNuLVRkHtQZb6k7vccDulrR8WKceMBDty4TYmZdAterNeU6pbEZecD/kJcojzvUZCmzuJkFY9I7fxDTm2IEJuqacrV7N5e1wpkRTGc68ivQKyWLz16bXo5QSa5ioFxgwHd7gd1k2heJ6OvZ5R2FDJw6teHXiplr0O4erVRQ==,iv:sHpKniwdQgZlCKEYzJYi4FDHKiNnZiXfFEeEWoNAYBc=,tag:rpLR2bcb8/DDkvz6ZeEpSw==,type:str]
    credentials.json: ENC[AES256_GCM,data:vmdHRGhd/897C805xDRRV4ingfDqEkXt4PzexjSOp8fBylzyEd1K5FIhzZ9be/WVDu2+rHnX7nvBQGM3qZWRzW+jkY4HbVnFu5twUf8MLaMN6MZlN61wYEDvtZeFHJe/998KRRcvMYVY74AOs/jh7ycnw+iqt04C/u00T4gu4Y/eQ/g=,iv:Jpi3UQH0vsbIdi8YmNoKFYW7o+Zvo9ltfuxla8JYxRs=,tag:xng8yQGlmZQsx7LDBvR0Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK0poZ3EvUDllZjFlMzdP
            VDY0M3NmTHpmNDVtYk9hdDZIdU5DV09YNWhNCkxWYTJ3QWVVRWpFckQ3cldQNHZN
            ZU9BUSt6cjd1cFY5ZzlXV2dUaHhVN00KLS0tIEgyUTFIczBkTlpIWTlVekl5REpL
            M1JDeDBSUmFRT0RNWUVpRXVoSElodGMKdPqYjg6+K9jffhybY1GXSNG1AzNwio+C
            CT4llqOfIvavscU+4cZbLjmzS943egN4eHb20vnljytli9ZCRUEHVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-23T07:39:03Z"
    mac: ENC[AES256_GCM,data:Edm79AiwV0evVphIurYGsdUpGjvZuT6Hsq0GTys2iD1GqJNUCTyFsvOZbpw035uiJhPFdxp9ixuvWyX+zg8DJuChDxsdvFmZmfkWxxR6ztRSZe01GpFX7kGNqlF5fP2ZJkflkjO6zwDdQ2cuJsvG9PwaIX/CJ0Pqxeil0ATrtLE=,iv:sRtvOlNVtP+MbDEkK0cb6cXuIA+r1OuJc9t+3EfZwA0=,tag:2pmoWggbnDojEl5SMhYLyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
