apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:e2C7fQgdUm4x+YLDOAEcLiY7ZlVzjsRhHFQ4O1h0JZUwIA/1,iv:OamI3nBT/M0AGEAJFOcZlZKKgHi1eETzNJsK+y3VTH4=,tag:xJIl6WeW9j+/93LDuvHIHQ==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:sUpiXGCd6m9Y4kF42TxZ0iM0y+yYvTnA74fDmc9VifOFA1b/XustGxKGgcy9fFwuMauvQx2HCA7+eWXalBkupZ7hEOwqWYrntpYKk5v+/E5p5LlGTpQQh1r3DoePVhQwwgxq06ikdPZeE6q/IiynrjmzlSAafwAcGmvrCZflwjiWgsEuQbDbwlD6GbvxRySh1j89bLFnotWHx7iRc1oHKUpXBZ4Ou6hjtTA8eL3ajbLgchBO+A7EqQ==,iv:IX38rpccW8QNwQaBdXNbZSAYkTmiUUOuAiPwq2j9OnQ=,tag:BPDjip5XTqP6lS1JMH1jXw==,type:str]
    credentials.json: ENC[AES256_GCM,data:0MURDINA+Duqs17WY7lrMI0OPrmCsm4487r/PWYmFzKEWbSsOqlo68Tl22J8LNxWjjlFAH2S4woWvEdkxruod4E0IyDow/EOSMC6XRd2EiPxQjfWBZTxxlaxZ0YMa0zv0sJ93lVIQ3f7zA2OUoO68J1Ipy5O0AD3tlijYANnyrZlxvQ=,iv:wlx2X5pPOlQXFDbt7T4kG9zBuvteqfLdGFfsAf5uFPg=,tag:34T2OAKjH/KdlVKkeFhllw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNmNKb1R6Wm9oUmoyVTNr
            Ukl2ZjcvaFRidHR3OW0zQldDRG1razVMY1NjCnJDVHpmekJieUpKYXlxREFKSmpX
            UjlUYjdvbHNGZUhnWlZwalM4V2VicWcKLS0tIG4rVHRPYTRhRGt0RUZPUmwvS1Fm
            Wko3TTlEbHQybzdjTW9BYTJ3aUhHamsKxZkz7csGbAVte/C62gaV5uC8Pq3skh0o
            Eh8TA3dmPbho71lxbwl8cqjo3lcimTFdCGVRUQpAOdweosX7Lu0gmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T05:18:52Z"
    mac: ENC[AES256_GCM,data:tmEhEpfNgojmwvAr9qAEW/I594/6QjUJQxqnHUXOPsgxIgPphsIhgJKFrxI38npM6fML6mLVxXJv8P76/dP1zKIK5EU8jqEwlHLlac7yR0UxGgLLGgUmHJOJHd78q4RiONjr69vr4sRUe/HXyM0BJG4aLD3hrh0o7zNPy9Kfv2c=,iv:sqJJtxyy5qmH28LzG1TKAwkDS7PPR8aAqxWEzKXNbgk=,tag:3YQ5VxpOgtrsxsCnLmQwSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
