---
kubernetes:
  children:
    controllers:
      hosts:
        "kube1":
          ansible_user: "kube"
          ansible_host: "192.168.0.56"
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        "kube2":
          ansible_user: "kube"
          ansible_host: "192.168.0.57"
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        "kube3":
          ansible_user: "kube"
          ansible_host: "192.168.0.58"
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
