apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:e8Ujdt0boQ0fypFpPlmfC9lAGWp7T//VtrK1IYp5Zj38FQaZS5/I8Q==,iv:K3BP1oSHCfzshbxCdaWqnxmio9Mhr0KVq3N0ActC6wM=,tag:MJefaAShyM624gvWmZvqjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcVFSaGxaMnlERlp0SUlB
            OEFNdm9UbDlrdUZkNkFITGJnL0xVb3Q0cTJzCjZoNFZqcGgxbkV0SCtRZHlkYUtZ
            ampYZ3JCWkw0RitUUkRSYVJiRlVYL3cKLS0tIExxclNkbFk1R1pUd3M3SWRpN29s
            eUdFQkU1dnhTM3FKZUhFeTY0UWtWdDQK6GDyCapbwh5/F8W88vHajUwzl7lB1ocn
            Zy2wFi/DgfdT0xKmvXqJChWLHiT7fAPtYB8EFld5xvqvFc8AjStkeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-06T07:21:28Z"
    mac: ENC[AES256_GCM,data:jrt4wN2G453Zmhb7AyqJyyTybqxJYpyo+fEmUvBeRhVQXk/i2lLKTj8AqSIx2qrVx1I8jT2rnwxYbKJYa2VTpCqivLDrIk5ltNURf3W+5m8uSv8xsVxpy+s3OnXRhIURbY5Pm8ENKrG6aWvJjTuLVPeXSJmUr4GRWcM/u1bcc8Q=,iv:p2XTB9rgERO5cJoEyqlUOt1YjwOJcKwgXcOUnQPUcXA=,tag:kfRFeMPbrnYniuLW34ji2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
