apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:JHg3qjyp4Mxva0l7JxeX0Ox32UN8qoPBWvgTS6oQdo4pjYQa+3Jn2w==,iv:ZuoK5CKQs4nj6hpwLjqnVdniEvivkfuUG7FY2tM5TH8=,tag:bcQGmTRifKrkG3uV0ErEzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRlIvUXl3dDRjMlcrRHBq
            eGpkQ0tUbEN3OWEyNzU4RzBqUXNxSjBOdzI0CnBPQVkwTTlja3hMYXpIbkxvTTJN
            TmplWlhDUTMwbGNVdDZBbFk5UU42K2MKLS0tIDNYdHR2OWF0ZlArL1dlTHJCTTJY
            NmdqbVVsTHRqdlFQd0pwaU15ZXV2RmcKBBgbNRCv65OZZKP1DFluFgTdFwUpz2N3
            bZuQcLsxhGHn0gu1Frlc8896Ubkhu87HtUu9nkSS8eVm7NohPANbfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T02:21:08Z"
    mac: ENC[AES256_GCM,data:citjNz9OihyS5BsJS1ZCKSMErUsDEfClLH6X6YLWXYwHUy7qMwUnXy0mqKfOLChdvr3ByEVSpLHUeDR42M1HWZFntiDQjau45/Ht853EjpXQZLMm1WD6mULiqDjR4axf89p61es7yWrheuPWmP72rGxCKSpHPpxX4gBry9/dM08=,iv:cIvJ0C+njkWtmzgy/37fbSwZ6AvgrndJQJymFA4SzG4=,tag:eeFgqaGUqTUQ+8AUu2qoJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
