##
# See https://metallb.io/configuration/#layer-2-configuration
#

apiVersion: metallb.io/v1beta2
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: network
spec:
  addresses:
  - 192.168.0.240-192.168.0.249
---
apiVersion: metallb.io/v1beta2
kind: L2Advertisement
metadata:
  name: default-l2
  namespace: network
spec:
  ipAddressPools:
  - default-pool
