---
# Copied from https://github.com/wrmilling/k3s-gitops/blob/main/kube-system/metallb/metallb.yaml

##
# MetalLB is a load-balancer implementation for bare metal Kubernetes clusters,
# using standard routing protocols.
# See https://metallb.universe.tf/
#

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.14.8
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 5m
  values:                 # See https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml
    crds:
      enabled: true
    # prometheus:
    #   serviceAccount: kube-prometheus-stack-prometheus
    #   namespace: monitoring
    #   podMonitor:
    #     enabled: true
    #   prometheusRule:
    #     enabled: true
    controller:       # controller contains configuration specific to the MetalLB cluster
                      # controller.
      enabled: true   # I basically put this there because I commented out everything else
      logLevel: info
      # tolerations:
      # - key: "arm"
      #   operator: "Exists"
    speaker:          # speaker contains configuration specific to the MetalLB speaker daemonset.
      enabled: true
      logLevel: info
      # tolerations:    # I dont want this but see https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
      # - key: "arm"
      #   operator: "Exists"
      # - key: "node-role.kubernetes.io/master"
      #   operator: "Exists"
