apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:dAYn6BgNlpl+6gnG+aEUcQTUh8JZE5uq2g3kLKvoM1PYdMxFiJUrL+UG2Nf6qOY5n8s/c7MouV5UCtqNzLpm40wbrbOtbQZfKGgAlA9MKl9rLzUh0K5QQXgGoUYozQ==,iv:OctSPDuUWnVFMXaIEr8xHhfUFShYslBxP3FA+w9EBiA=,tag:kAoNvZ93bfl4bEnHqm1gLA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:kXMBxbuzYgsUlxt2,iv:1tk6dc+4HhauaQ4ZAb6SI2yxldc6Nqs5j0Yb1vG1Nhg=,tag:TDisVwPnbzKqT7AaJxyE0g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8St+KFUHm1yTpFHrwbon0j9j,iv:81iXkKrmG0Qpej9yPbsEI/PQxIQvMVEMa+9D+2HZBUs=,tag:jJJokvIb6syMMi4ixLVaAw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KxPQ8T5q24t9CykX4bWfbG+PBPvxH8e4uCyBP7StgMi4MOpc,iv:BcPJCDgMmPvsH1RRiuxgkn9BXUGusbpkYhDuBOgebqs=,tag:U2B2+eNDJZE2GwHjz6SQQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc2NqTlRQVlpPWWI1SXoy
            dmNJS3o0OTQwMHhzMzN0dzJGdnNyMU92LzNzCkVDMnRRLzJpY1crVXQ1OUxEbnBt
            WTdZT2FYdUc3ZDVqaSttd2ZTUmRPeEUKLS0tIGRBY1BRMk9ENm5pV1NwR1VWT0Vq
            dTFiR0QwUTZjdHVKdmU4dS9IU2VML2MKVocQEmKsd7wSPonENbRxPVVtoS7WsEzB
            3JfNNzlSyaIYrEukyotjSMZY7YDEwQf7f4U015jrzsCCpa65Tq6AZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T06:20:43Z"
    mac: ENC[AES256_GCM,data:VF3Mzek/fI0vL6/Jc8tOB3Uke9plepG3aLLLzqSrnECv7vH8OD1OX+PPGB4tAkpb0S4ZWhPuzItCA/KTbBAJK10a6rkoqwWoybcBwH9D8nIP8sf292Ybi2Ndi0iQElya0hPniCbSbKUm5MGpQx5k5SXgQActg4XBm/uTUMnwrcg=,iv:rvjSTRcipyBNDT71ttpDSi4J+kPmTYTj7akMj4K0MoE=,tag:SQRWrsSlKKnkhULPoeEGvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
