# Experimenting...

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: octoprint
spec:
  interval: 1h
  chart:
    spec:
      chart: octoprint
      version: TODO
      sourceRef:
        kind: HelmRepository
        name: octoprint
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    # ignore:
      # Ignore "validated" annotation which is not inserted during install
      # - paths: [ "/metadata/annotations/prometheus-operator-validated" ]
      #   target:
      #     kind: PrometheusRule
  valuesFrom:
  - kind: ConfigMap
    name: octoprint-config
    valuesKey: octoprint-config.yaml
