apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:riUb6jHn5sLSxBDIhuntxAzfD1sO461AhDZbiUvwkdo=,iv:sQBHQ8ngGiTR2UFfrrB1fJC0sGQPEwNsBDPBswCY0MU=,tag:GzDOlBOBaZ8Ndcdl8rZFSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcjhYUEFwVG5vTVVReTRi
            NFdHQSszVU9CRnJaSU5JVE1KWGJTMFlLNEhNCkhKNXZRbllTK3ROMHpGVHgzUURz
            L2FXekM2ZUs3dUQ0ZS9CRkpPOE1wR2sKLS0tIEt5ZzA2Z2cvOFhVeDdNN3ZQK20r
            VGpBWlJNalNGR3RsaVo5My9SNXNRVDgKYnLiLJ1yPf4IEprvWuw7TKYn+AvR+GEc
            2uezwHy1tCrjuk88vWnGB58gx1DyUj/M4RAQUNbeB7J6giktKt40Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-22T03:14:48Z"
    mac: ENC[AES256_GCM,data:4VC0SCxcIEC7i7WxVk0whf2C0Fv9ljdMxmwDbf7+sHF4QshDre5jBQF2TLwNvjspQ6CDueuCsro8Pay6Zfl8/fISESJRdhqUXpFkg0StSClmcssRWTtpbWTY9hIRl7ZwOpVc8s//8yXXh1sG13MOWoslqre6XlsX+AWHxItR77g=,iv:w8IGjlq2eSiP+QNlHBTpR5c0FcC730QOTyBtfyWWJGM=,tag:VfmA5/ABTb65eVkr3NVKQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
