apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:00+NwAKIgLrp2Kfp7+GOk2piqsfy7QzH2ojRj81hiJ8=,iv:t+uvP/rQE6juvd+bEXVy2MS12jPeRGpq0mNri7akzaA=,tag:9kuGuYPjlKEscnkzQHi87A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNWVzdkpOOXdIU2RwSnRs
            U3V6ZkJtRWFhV2FLdExudldHdXVXVHZ5TENjCkJMT0RLUXJPUGRTRm0vb2FDZG85
            Yjk0RDI0K0tjOXdPZXlkM1MwK3VyMnMKLS0tIHNQRVBqMUt0SWM2VGduNXVJMU01
            Vm5qYy9FOEFDSlRtdGd5cFFZbS9DcHMKdxMeJFkBJQJ9uGPScUdFAJpzZ6bctB8T
            QHktPAbMWPd87WaMJjZeK69e4gfIqiMYZZl/oh8pgkvkbg7BHjEI4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T07:30:54Z"
    mac: ENC[AES256_GCM,data:/mJijPzr5IAMGHq5UbDUe6l65FHTFt3ngtP0gEQbTeWsq44TJJD/tMApo1kt19OPOgs+XK5OHafcZukZVBmccgChz/NAZYJRGgNlNdiNA9UFB1EwUo9ARnIG+Dz+sHM6tJ+fTyzGSHkMDxltrg60dzOG5n1/o6T4+XHrbaicZMA=,iv:DoZ1YQ/6Cp84ogdosRVOeNrOBhK6jkqWvNV8X84WoyY=,tag:Guc4O4ZSmhzaluF91+Va3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
