---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshtest
  namespace: network
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
