# This was my attempt to use a SOPs secret instead of the externalSecret from onedr0p
# Not in play as yet.
# Also not sure what the data structure should be.  In the external secret it seems to be an object rather than a key-value
# not sure if you can do that with a Secret...
#
apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard
stringData:
    password: ENC[AES256_GCM,data:pxkoyUpJlXC5SB9Qo7c=,iv:myn9bTwrAAjGB0X6TFbJWxa4O7r57sC8fBx07nB2cio=,tag:dYhALqdWEPLgBFtS6lmB1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFclhINXFDcVhucnUrdUJl
            SlgxNTlsR29WK2tkKytWbFBLSnFJbnR2VlhZClVhQVY2TTNkWHZlV3lJVSsyY214
            UGZyS1pvSzdWcjdXRm5PUHkvOHorSVEKLS0tIHZDZTU5Wi9hY3l1SVR5UzMzUE4z
            QUZXZjNvd3FORjQwRVlaRE03Nkk5YU0KnvcAYZBsmixXoW7n0p5WeyJFcUwqY3PS
            M01iYWxlo06AvYZAUvRZsc5JbN/GX6sk5ywzm329oCgsu1+6ClMHVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-11T02:54:50Z"
    mac: ENC[AES256_GCM,data:9BiqLqxrNlaxDZ7DNjqFFPSLH2CMjOvottRAfeUL/WCrYCzHoJj6IrYGHvCsh5FAQ919Jup93SIraiFZp6hIJS6BCgrvQHwSfokiVYQdMRY8zGLM3lq78Jf/OS/SNzz3hmO44OMaQDfnaJmO7YmLx7QONefKSG2pIPClygNM+7M=,iv:5XvQsMrD0jtAlaF6V+cMmfM7HnZSdnAyIcnh8YDV/kY=,tag:ZMDBGRnt9jjd0JvzTG4yfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
