# This was my attempt to use a SOPs secret instead of the externalSecret from onedr0p
# Not in play as yet.
# Also not sure what the data structure should be.  In the external secret it seems to be an object rather than a key-value
# not sure if you can do that with a Secret...
#
apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard
stringData:
    password: hT%gRYPEau4kY&
