apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:YX9OHsBBX1132zu+G2qPdMuobPHQ+CgUduHh+3etMHk6JXJgRK8KbA==,iv:cazpj8Vf0vf2ey6/CqT02jl9aZwHFNdlI9JOd4uLGAU=,tag:aDxHubiI0OXsmFU0BQ9zpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZVNPK3ZzeHdtOFFyVzd6
            cXJhSVpDbkR6R05qL2RwZ1plbFZvMnBJeXpJCmdzVjdqbm9UdW5TdWJoallMV3RD
            ZVA4WXBjcHlNZUdEZWh6QzVXVWFESkEKLS0tIC9KcmJFWDdQQ0NMQS9kc1Jrbng1
            YXBJL1hlMHlic05oMWx1ZnMyOStlcG8KWvW8dMY0qHxuDeyy1G4VfnMQephhpDkb
            FohittRGmbLBWCLRanvqq6a5K9o/iI3C+I59uu+P/NgkfsZh0N3dTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T08:12:23Z"
    mac: ENC[AES256_GCM,data:KeqjrmsCuJQK1ts2+1w4P7gUoAYm/J742JIC2OjUf4Payti+YK9ZnJPMR5Y9mDgObLJv+BXTqZeWPrY7sWltHWl2eXijDE4Z52gjEo3znsJr4YRSCU9MHcd6+OMnUGIFavHvwvkiDWFoqb9JwMGbAxK2X/Bpty/7FHnFdn/Krvg=,iv:tyyUobyLGOgyLeQ4E5zStRHFqRt5xpFGdjNeSpTVHXU=,tag:K00zKgsb/73SELQVlyg5ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
