apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ff4peppl5cOAtsrg9bY9XrzBpG6FskyQjaXvPfPdbjUjjPlXWJeyFg==,iv:NjlykDTuZcTF8t+uc2LgyhojBzWExYfRxXJlS2YEqWg=,tag:dmXsIiPKyyCEtf+iB8CohA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZTBqTlExa0hKQ0NkdFAr
            VHhEem14eTdrbWpFMHNua3ZiK1RQZWhBdm5ZCkNKQUJaTUR4aWZpd2w0QmpsK09x
            YTZwejgvUkNIeHp5clQ3am1MdVphMlUKLS0tIDNlbnhjSkFReDRZWHZ4UWtwNGp0
            dklZNUg1TTVEYkFCQ2p0M3VxWlhTU28KmruD0ZztwsseKC/c0InxjQEXrqC2hlYt
            wSojP42eKquu72RJ9NxzPKZKkBPayy+4Htwsg/CzMlRcdVM3Xq4VuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T07:30:54Z"
    mac: ENC[AES256_GCM,data:oTtE0+tWdAvZK3wXx1Zx/NI1mArme2ynsb+HOAQRNyG7S/kuBOE3o7sqocj1zBbVQUaisB0blmni3OcRM+neGIHAxzgp9ISVCmjj+qP9OrGxysndXad/hrr/8TZZ8+1l7wTc0YikDsXO7nS9HSoklk1u2CHoqQmin1P9sEy/Knc=,iv:E6V24pIVVldNW68bwv72bXZnHHImMNgXMMXAGOPkP2U=,tag:KEL5NAM+yb3DUDWTtALKmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
