apiVersion: v1
kind: Secret
metadata:
    name: pihole-secrets
stringData:
    password: ENC[AES256_GCM,data:om8iF5ptptWT+Qy7X3Y=,iv:vYK9ZuSOaUhqXDgEWcZy2xTyHIQPrXCcDvVx0wXEsKM=,tag:unxKF/ZpiUx+Q3161yQ2pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gmx07m628g7qhhgtfrm9rhcau988gtw358yjqyeu9wxcyype0a9qu2r0a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWWFkbXY1d21vNXFpaGgw
            RUdJdG1JTlg3VEgxSWFuMFNpR3hhc0pURmdzCm1PMlJ6TXpqUmRLK3UyTFRRdDRs
            eGVvTzZQTi9tcmx0ZFduaEZZTm5xcUUKLS0tIGhnL3V6QU82Q28xYmg3eFJYOU1E
            blBRZGhQNXJ3THJhcW1QazkyVjlEeVEK5y/DUyge5YdY+3FbEkAN5WInQe+Sw0il
            LEXDuuvM4xVJuit4M3c0bzmQ0JEfL9OwHqUwFDK8J3Ok+9fyM+GpMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T10:03:22Z"
    mac: ENC[AES256_GCM,data:nJuH49rdW3qhCuGZVS9SyVMVHvq0MYg/mIK5GHBZGsf1jf7vOx5rZ8goOrh9LAVGei05FrGlsmMGi4EUYmTWTF8cJ23Xr5OGf/OKZ9apCQvHvsHVQtJ9fC+N82QQRnNRMwbCxXlwxx2LhmprqvAaorB3cyriO9LOTtmKNbWf4JY=,iv:sF2VXjGtuWO+vr+m23EeKOVZa1xQEy5gVc4illZ5wQQ=,tag:XAmpRGK50Bpd8aIK6yUytg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
