---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudflared/ks.yaml
  - ./echo-server/ks.yaml
  # - ./echo-server2/ks.yaml  # just testing how to add apps
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./pihole/ks.yaml
  # - ./metallb/ks.yaml
