---
# Copied from joryirving/home-ops
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./openebs/ks.yaml # I already have this in the openebs-system namespace
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
